services:
  # Шард 1
  postgres-shard1:
    image: postgres:18
    environment:
      POSTGRES_DB: shard1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_shard1_data:/var/lib/postgresql/18/docker
    networks:
      - shard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB

  # Шард 2
  postgres-shard2:
    image: postgres:18
    environment:
      POSTGRES_DB: shard2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_shard2_data:/var/lib/postgresql/18/docker
    networks:
      - shard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB

  # Шард 3
  postgres-shard3:
    image: postgres:18
    environment:
      POSTGRES_DB: shard3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_shard3_data:/var/lib/postgresql/18/docker
    networks:
      - shard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB

  # FastAPI приложение
  sharding-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL_SHARD1=postgresql://postgres:password@postgres-shard1:5432/shard1
      - DATABASE_URL_SHARD2=postgresql://postgres:password@postgres-shard2:5432/shard2
      - DATABASE_URL_SHARD3=postgresql://postgres:password@postgres-shard3:5432/shard3
    depends_on:
      postgres-shard1:
        condition: service_healthy
      postgres-shard2:
        condition: service_healthy
      postgres-shard3:
        condition: service_healthy
    networks:
      - shard-network
    volumes:
      - ./app:/app

volumes:
  postgres_shard1_data:
  postgres_shard2_data:
  postgres_shard3_data:

networks:
  shard-network:
    driver: bridge